theme: jekyll-theme-modernist

disqus:
  shortname: shea08

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

title: Ben Shea <a href="https://shea08.github.io"><font size="-2">[shea08.github.io]</font></a>
description: A shared spot for a passion in technology - science - and how it works

---
layout: default
comments: true
# other options
---
