theme: jekyll-theme-leap-day

disqus:
  shortname: shea08

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

title: <a href="https://shea08.github.io">B</a>en Shea
description: A shared spot for a passion in technology - science - and how it works
---
layout: default
comments: true
# other options
---
