theme: jekyll-theme-leap-day

disqus:
  shortname: shea08

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

title: <a href="https://shea08.github.io">B</a>en Shea
description: A shared spot for a passion in technology - science - and how it works
<meta name="google-site-verification" content="YzxQW1uWDOXrLhdyd4E8neU7wAOv3quWXF1Sl5pZiD0" />
---
layout: default
comments: true
# other options
---
