theme: jekyll-theme-leap-day

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

title: <a href="https://shea08.github.io">Ben Shea</a>
description: A shared spot for a passion in technology - science - and how it works
