theme: jekyll-theme-leap-day

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

title: Ben Shea
description: <a ref= "shea08.github.io"> A shared spot for a passion in technology - science - and how it works </a>

favicon: icons8-robot-64.png
